### ISSUE TITLE
Failing to import Obj-C header 

### ISSUE THREAD

**Issue by rymir** [curoo/ConfidoIOS#14]
Using ConfidoIOS as a pod, fails on build time with:

<img width="1178" alt="screen shot 2015-12-06 at 17 28 47" src="https://cloud.githubusercontent.com/assets/2323918/11614594/f7800520-9c3e-11e5-8362-48192a04a5f6.png">

there is no such header as `/usr/include/CommonCrypto/CommonCrypto.h` on my system, maybe we should use some sort of `CommonCrypto` wrapper like https://github.com/soffes/Crypto

**Comment by benjaminboxler** [comment]
I had a similar issue. Should be a symlink there. Fixed by running
`xcode-select install` on my machine

**Comment by rymir** [comment]
shouldn't the path be pointing to a `XCode` location as in https://github.com/henrinormak/Heimdall/tree/master/CommonCrypto?

**Comment by psytale** [comment]
Think the idea was this means you don't have to have separate modulemaps
for each of the targets, but does need a little bit extra of set up.

**Comment by rymir** [comment]
I got this problem after upgrading to OSX El Capitan, for some reason I had to reinstall XCode command line tools and now I have the headers in `/usr/include/..`.

**Comment by rymir** [comment]
Being it a public repository maybe we should state on the README that it requires XCode command line tools installed (`xcode-select --install` as @benjaminboxler pointed out)

**Comment by benjaminboxler** [comment]
Yeah, it was updating to El C that I couldn't update. Make a PR that adds it to the readme
